### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by chauthehan** [manhph2211/BKAI-Challenge-Vietnamese-OCR#1]
Bạn ơi, cho mình xin data của cuộc thi mình training thử được không ạ

**Comment by ngocphucck** [comment]
Đây là tập public dataset và private dataset mà nhóm chúng mình được sử dụng trong cuộc thi:

- [public dataset 1](https://drive.google.com/drive/folders/1WNOk3EMSgawdbrHeLiO7N_WcapgmbdmV)
- [public dataset 2](https://drive.google.com/file/d/1UUQhNvzgpZy7zXBFQp0Qox-BBjunZ0ml/view?usp=sharing)
- [private dataset](https://drive.google.com/drive/folders/14jV4W7Cdz5Q-znwhY0GenLrWzKbgS4ah?usp=sharing)
